double ffn_rate_nue(double, double, int, int);
double ffn_rate_nuebar(double, double, int, int);
double weak_R(double, double, int, int);
double weak_Q(double, double, int, int);
double fd_norm(double, double);
double Q_eff_capture(double, double, double, double);
double Enu_avg_capture(double, double, double);
double effective_capture_rate(double, double, double);
double Q_eff_decay(double, double, double, double);
double Enu_avg_decay(double, double, double);
double effective_decay_rate(double, double, double);
double Enu_avg_capture_and_decay(double, double, double);
double Q_eff_capture_and_decay(double, double, double, double, double);
double neutron_R(double, double);
double proton_R(double, double);
double neutron_Q(double, double);
double proton_Q(double, double);
double NSE_neutrino_spectrum(double, double, double, double, int); 
double NSE_neutrino_spectrum_tbl(double, double, double, double, int); 
void   NSE_neutrino_spectrum_table(double*, double, double, double, double, int, double, double ,int, int); 
void   NSE_nuclei_neutrino_spectrum_table(double*, double, double, double, double, int, double, double ,int, int); 
void   NSE_nucleons_neutrino_spectrum_table(double*, double, double, double, double, int, double, double ,int, int); 
double NSE_neutrino_Q(double, double, double, double, int, int, int);
double NSE_neutrino_R(double, double, double, double, int, int, int);
double NSE_neutrino_Q_old(double, double, double, int, int, int);
double NSE_neutrino_R_old(double, double, double, int, int, int);
double capture_integral(double, double, double Q);